### ISSUE TITLE
gulp error

### ISSUE THREAD

**Issue by PatrickJS** [mgechev/angular.hs#1]
```
[14:25:41] TypeError: object is not a function
    at Gulp.<anonymous> (/Users/patrick/Documents/open-source/angular.hs/gulpfile.js:9:10)
    at module.exports (/Users/patrick/Documents/open-source/angular.hs/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/patrick/Documents/open-source/angular.hs/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/patrick/Documents/open-source/angular.hs/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/patrick/Documents/open-source/angular.hs/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at /Users/patrick/.nvm/versions/node/v0.12.4/lib/node_modules/gulp/bin/gulp.js:129:20
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by mgechev** [comment]
Yeah, nothing works currently. This error comes from `gulp-haste`, however internally it uses `gulp-shell` and the haste compiler.

Still not able to make `haste` run on my local machine...I guess I'll push this project into my projects-queue.
